services:
  web:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
    image: hacktracker:latest
    container_name: hacktracker
    restart: unless-stopped
    ports:
      - "80:3000"
    env_file:
      - .env
