[phases.setup]
nixPkgs = ["nodejs_18", "pnpm-9_x", "openssl"]

[phases.install]
cmds = ["cd web && pnpm install"]

[phases.build]
cmds = ["cd web && pnpm build"]

[start]
cmd = "cd web && pnpm start"
